In [1]:
# Attributes of array
# index
# slicing
# Reshaphing
# joining and Splitting

# 1. Array Attributes 

In [2]:
import numpy as np
np.random.seed(0) # Seed ti initial
x1 = np.random.randint(10, size = 6) # one dimension
x2 = np.random.randint(10, size = (3,4)) # two dimension
x3 = np.random.randint(10, size = (3,4,5)) # three dimension

#ndim

In [3]:
print("x3 dimension1: ", x3.ndim)
print("x3 dimension2: ", x3.shape)
print("x3 dimension3: ", x3.size)

x3 dimension1:  3
x3 dimension2:  (3, 4, 5)
x3 dimension3:  60


In [4]:
#dtype
print("data type:", x3.dtype)

data type: int32


In [5]:
#itemsize
print("item size of the array: ", x3.itemsize, "bytes")
print("item size of the array: ", x3.nbytes, "bytes")


item size of the array:  4 bytes
item size of the array:  240 bytes


In [6]:
print("x2 dimension: ", x2.ndim)
print("x2 dimension: ", x2.shape)
print("x2 dimension: ", x2.size)

x2 dimension:  2
x2 dimension:  (3, 4)
x2 dimension:  12


In [7]:
print("item size of the array: ", x2.itemsize, "bytes")
print("item size of the array: ", x2.nbytes, "bytes")


item size of the array:  4 bytes
item size of the array:  48 bytes


# Array indexing

In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]

5

In [10]:
x1[4]

7

In [11]:
x1[-3]

3

In [12]:
x1[-1]

9

In [13]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
x2[2,1]

6

In [15]:
x2[0,0]

3

In [16]:
x2[2,3]

7

In [17]:
x2[2,-2]

7

In [18]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [19]:
x2[-3,-3]

5

In [20]:
x2[2,3]= 12

In [21]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 12]])

In [22]:
x2[-2,-2] = 9

In [23]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  9,  8],
       [ 1,  6,  7, 12]])

In [26]:
x2[-2,-2]= 13.9

In [27]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

# Slicing

In [ ]:
#x[start:stop:step]

In [28]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[0:5]

array([0, 1, 2, 3, 4])

In [30]:
x[3:7]

array([3, 4, 5, 6])

In [31]:
x[::2]

array([0, 2, 4, 6, 8])

In [32]:
x[1::2]

array([1, 3, 5, 7, 9])

In [33]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
x[::-2]

array([9, 7, 5, 3, 1])

In [36]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [ ]:
#x2[start:stop:step, start:stop:step]

In [37]:
x2[:2, :3]

array([[ 3,  5,  2],
       [ 7,  6, 13]])

In [38]:
x2[:3, ::2]

array([[ 3,  2],
       [ 7, 13],
       [ 1,  7]])

In [39]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [40]:
x2[::-1,::-1]

array([[12,  7,  6,  1],
       [ 8, 13,  6,  7],
       [ 4,  2,  5,  3]])

In [42]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [41]:
print(x2[:,0]) # all rows 0 column

[3 7 1]


In [43]:
print(x2[0,:])

[3 5 2 4]


In [44]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [45]:
print(x2[0:1, 0:2])

[[3 5]]


In [46]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [47]:
print(x2[2:, 2:])

[[ 7 12]]


In [48]:
print(x2[-1:, -2:])

[[ 7 12]]


In [49]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [50]:
print(x2[0:1,:])

[[3 5 2 4]]


# Subarray with no copy

In [51]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [52]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [53]:
x2_sub[0,0] = 99

In [54]:
x2

array([[99,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

# with copy

In [55]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [56]:
x2_sub_copy[0,0] = 7

In [57]:
x2_sub_copy

array([[7, 5],
       [7, 6]])

In [58]:
x2

array([[99,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

# Reshape

In [59]:
grid = np.arange(1,10).reshape((3,3))

In [60]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [62]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [64]:
x

array([1, 2, 3])

In [63]:
# column vector via newaxis

x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [65]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [66]:
y= x[:,np.newaxis]

In [67]:
y

array([[1],
       [2],
       [3]])

In [68]:
x

array([1, 2, 3])

In [70]:
y.shape

(3, 1)

In [71]:
y[np.newaxis,:]

array([[[1],
        [2],
        [3]]])

In [72]:
y.reshape((1,3))

array([[1, 2, 3]])

In [73]:
y

array([[1],
       [2],
       [3]])

In [74]:
x

array([1, 2, 3])

In [ ]:
#np.newaxis / reshape

# Array Concatenation

In [ ]:
# np.concatenate
# np.vstack
# np.hstack

In [75]:
x

array([1, 2, 3])

In [76]:
y = np.array([3,2,1])

In [77]:
y

array([3, 2, 1])

In [78]:
z=np.concatenate([x,y])

In [79]:
z.shape

(6,)

In [80]:
z.ndim

1

In [81]:
z.size

6

In [82]:
z

array([1, 2, 3, 3, 2, 1])

In [83]:
a = [99,99,99]
np.concatenate([x,y,a])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [84]:
d2 = np.array([[1,2,3],
              [4,5,6]])

In [85]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
d2_con = np.concatenate([d2,d2])

In [87]:
d2_con

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [88]:
d2_con1 = np.concatenate([d2,d2], axis = 1)

In [89]:
d2_con1

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [90]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
y

array([3, 2, 1])

In [92]:
x2

array([[99,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [93]:
d2 = np.array([[1,2,3,4],
              [4,5,6,7],
              [7,8,9,10]])

In [94]:
d2

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [95]:
np.concatenate([d2,x2])

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [99,  5,  2,  4],
       [ 7,  6, 13,  8],
       [ 1,  6,  7, 12]])

In [96]:
np.concatenate([x2,d2], axis = 1)

array([[99,  5,  2,  4,  1,  2,  3,  4],
       [ 7,  6, 13,  8,  4,  5,  6,  7],
       [ 1,  6,  7, 12,  7,  8,  9, 10]])

In [97]:
x = np.array([1,2,3])
grid = np.array([[4,5,6],
                [7,8,9]])
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
v = np.array([[99],
             [99]])
v

array([[99],
       [99]])

In [99]:
np.hstack([v, grid])

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])

In [ ]:
# split
# hsplit
# v split

x=[1,2,3,4,5,6,7,8]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

In [ ]:
x11,x21, x31 = np.split(x,[3, 6])

In [ ]:
print(x11, x21, x31)

In [ ]:
grid1 = np.arange(16).reshape((4,4))
grid1

In [ ]:
up, down = np.vsplit(grid1, [2])
print(up)
print(down)

In [ ]:
lef, rig = np.hsplit(grid1, [2])
print(lef)
print(rig)